# Generated by Django 4.2.5 on 2023-09-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='почта')),
                ('login', models.CharField(max_length=200, verbose_name='логин')),
                ('password', models.CharField(max_length=28, verbose_name='пароль')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='баланс')),
            ],
            options={
                'verbose_name': 'полтзователь',
                'verbose_name_plural': 'полтзователи',
                'ordering': ('-id',),
            },
        ),
    ]
