# Generated by Django 4.2.4 on 2023-10-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='кол-во товара'),
        ),
    ]
