# Generated by Django 4.2.5 on 2023-09-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_delete_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='комментарий')),
                ('game_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='игра')),
            ],
            options={
                'verbose_name': 'коммент',
                'verbose_name_plural': 'комментарии',
                'ordering': ('-id',),
            },
        ),
    ]
